//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ipg
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Kimia.org/", ConfigurationName="ipg.KimiaPayGatewayVerifyWSrvcSoap")]
    public interface KimiaPayGatewayVerifyWSrvcSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/TestService", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.TestServiceResponse> TestServiceAsync(ipg.TestServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnVerifyPayGatewayByDocNo", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayByDocNoResponse> pubFunBlnVerifyPayGatewayByDocNoAsync(ipg.pubFunBlnVerifyPayGatewayByDocNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnVerifyPayGateway", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayResponse> pubFunBlnVerifyPayGatewayAsync(ipg.pubFunBlnVerifyPayGatewayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnRegOnlineReverse", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineReverseResponse> pubFunBlnRegOnlineReverseAsync(ipg.pubFunBlnRegOnlineReverseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnRegOnlineConfirm", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineConfirmResponse> pubFunBlnRegOnlineConfirmAsync(ipg.pubFunBlnRegOnlineConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnAcptrVlid", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnAcptrVlidResponse> pubFunBlnAcptrVlidAsync(ipg.pubFunBlnAcptrVlidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Kimia.org/pubFunBlnGetServrDatTim", ReplyAction="*")]
        System.Threading.Tasks.Task<ipg.pubFunBlnGetServrDatTimResponse> pubFunBlnGetServrDatTimAsync(ipg.pubFunBlnGetServrDatTimRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestService", Namespace="http://Kimia.org/", Order=0)]
        public ipg.TestServiceRequestBody Body;
        
        public TestServiceRequest()
        {
        }
        
        public TestServiceRequest(ipg.TestServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestServiceRequestBody
    {
        
        public TestServiceRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.TestServiceResponseBody Body;
        
        public TestServiceResponse()
        {
        }
        
        public TestServiceResponse(ipg.TestServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class TestServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestServiceResult;
        
        public TestServiceResponseBody()
        {
        }
        
        public TestServiceResponseBody(string TestServiceResult)
        {
            this.TestServiceResult = TestServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnVerifyPayGatewayByDocNoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnVerifyPayGatewayByDocNo", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnVerifyPayGatewayByDocNoRequestBody Body;
        
        public pubFunBlnVerifyPayGatewayByDocNoRequest()
        {
        }
        
        public pubFunBlnVerifyPayGatewayByDocNoRequest(ipg.pubFunBlnVerifyPayGatewayByDocNoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnVerifyPayGatewayByDocNoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmAcptrCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmTrmnlCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmReqData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmRetData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string prmStrErr;
        
        public pubFunBlnVerifyPayGatewayByDocNoRequestBody()
        {
        }
        
        public pubFunBlnVerifyPayGatewayByDocNoRequestBody(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmRetData, int prmResult, string prmStrErr)
        {
            this.prmAcptrCod = prmAcptrCod;
            this.prmTrmnlCod = prmTrmnlCod;
            this.prmReqData = prmReqData;
            this.prmRetData = prmRetData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnVerifyPayGatewayByDocNoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnVerifyPayGatewayByDocNoResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnVerifyPayGatewayByDocNoResponseBody Body;
        
        public pubFunBlnVerifyPayGatewayByDocNoResponse()
        {
        }
        
        public pubFunBlnVerifyPayGatewayByDocNoResponse(ipg.pubFunBlnVerifyPayGatewayByDocNoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnVerifyPayGatewayByDocNoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnVerifyPayGatewayByDocNoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmRetData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmStrErr;
        
        public pubFunBlnVerifyPayGatewayByDocNoResponseBody()
        {
        }
        
        public pubFunBlnVerifyPayGatewayByDocNoResponseBody(bool pubFunBlnVerifyPayGatewayByDocNoResult, string prmRetData, int prmResult, string prmStrErr)
        {
            this.pubFunBlnVerifyPayGatewayByDocNoResult = pubFunBlnVerifyPayGatewayByDocNoResult;
            this.prmRetData = prmRetData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnVerifyPayGatewayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnVerifyPayGateway", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnVerifyPayGatewayRequestBody Body;
        
        public pubFunBlnVerifyPayGatewayRequest()
        {
        }
        
        public pubFunBlnVerifyPayGatewayRequest(ipg.pubFunBlnVerifyPayGatewayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnVerifyPayGatewayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmAcptrCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmTrmnlCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmReqData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmRetData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string prmStrErr;
        
        public pubFunBlnVerifyPayGatewayRequestBody()
        {
        }
        
        public pubFunBlnVerifyPayGatewayRequestBody(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmRetData, int prmResult, string prmStrErr)
        {
            this.prmAcptrCod = prmAcptrCod;
            this.prmTrmnlCod = prmTrmnlCod;
            this.prmReqData = prmReqData;
            this.prmRetData = prmRetData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnVerifyPayGatewayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnVerifyPayGatewayResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnVerifyPayGatewayResponseBody Body;
        
        public pubFunBlnVerifyPayGatewayResponse()
        {
        }
        
        public pubFunBlnVerifyPayGatewayResponse(ipg.pubFunBlnVerifyPayGatewayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnVerifyPayGatewayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnVerifyPayGatewayResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmRetData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmStrErr;
        
        public pubFunBlnVerifyPayGatewayResponseBody()
        {
        }
        
        public pubFunBlnVerifyPayGatewayResponseBody(bool pubFunBlnVerifyPayGatewayResult, string prmRetData, int prmResult, string prmStrErr)
        {
            this.pubFunBlnVerifyPayGatewayResult = pubFunBlnVerifyPayGatewayResult;
            this.prmRetData = prmRetData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnRegOnlineReverseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnRegOnlineReverse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnRegOnlineReverseRequestBody Body;
        
        public pubFunBlnRegOnlineReverseRequest()
        {
        }
        
        public pubFunBlnRegOnlineReverseRequest(ipg.pubFunBlnRegOnlineReverseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnRegOnlineReverseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmAcptrCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmTrmnlCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmReqData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prmStrErr;
        
        public pubFunBlnRegOnlineReverseRequestBody()
        {
        }
        
        public pubFunBlnRegOnlineReverseRequestBody(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmResult, string prmStrErr)
        {
            this.prmAcptrCod = prmAcptrCod;
            this.prmTrmnlCod = prmTrmnlCod;
            this.prmReqData = prmReqData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnRegOnlineReverseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnRegOnlineReverseResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnRegOnlineReverseResponseBody Body;
        
        public pubFunBlnRegOnlineReverseResponse()
        {
        }
        
        public pubFunBlnRegOnlineReverseResponse(ipg.pubFunBlnRegOnlineReverseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnRegOnlineReverseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnRegOnlineReverseResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmStrErr;
        
        public pubFunBlnRegOnlineReverseResponseBody()
        {
        }
        
        public pubFunBlnRegOnlineReverseResponseBody(bool pubFunBlnRegOnlineReverseResult, string prmResult, string prmStrErr)
        {
            this.pubFunBlnRegOnlineReverseResult = pubFunBlnRegOnlineReverseResult;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnRegOnlineConfirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnRegOnlineConfirm", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnRegOnlineConfirmRequestBody Body;
        
        public pubFunBlnRegOnlineConfirmRequest()
        {
        }
        
        public pubFunBlnRegOnlineConfirmRequest(ipg.pubFunBlnRegOnlineConfirmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnRegOnlineConfirmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmAcptrCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmTrmnlCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmReqData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prmStrErr;
        
        public pubFunBlnRegOnlineConfirmRequestBody()
        {
        }
        
        public pubFunBlnRegOnlineConfirmRequestBody(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmResult, string prmStrErr)
        {
            this.prmAcptrCod = prmAcptrCod;
            this.prmTrmnlCod = prmTrmnlCod;
            this.prmReqData = prmReqData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnRegOnlineConfirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnRegOnlineConfirmResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnRegOnlineConfirmResponseBody Body;
        
        public pubFunBlnRegOnlineConfirmResponse()
        {
        }
        
        public pubFunBlnRegOnlineConfirmResponse(ipg.pubFunBlnRegOnlineConfirmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnRegOnlineConfirmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnRegOnlineConfirmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmStrErr;
        
        public pubFunBlnRegOnlineConfirmResponseBody()
        {
        }
        
        public pubFunBlnRegOnlineConfirmResponseBody(bool pubFunBlnRegOnlineConfirmResult, string prmResult, string prmStrErr)
        {
            this.pubFunBlnRegOnlineConfirmResult = pubFunBlnRegOnlineConfirmResult;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnAcptrVlidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnAcptrVlid", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnAcptrVlidRequestBody Body;
        
        public pubFunBlnAcptrVlidRequest()
        {
        }
        
        public pubFunBlnAcptrVlidRequest(ipg.pubFunBlnAcptrVlidRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnAcptrVlidRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmAcptrCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmTrmnlCod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmReqData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prmStrErr;
        
        public pubFunBlnAcptrVlidRequestBody()
        {
        }
        
        public pubFunBlnAcptrVlidRequestBody(string prmAcptrCod, string prmTrmnlCod, string prmReqData, int prmResult, string prmStrErr)
        {
            this.prmAcptrCod = prmAcptrCod;
            this.prmTrmnlCod = prmTrmnlCod;
            this.prmReqData = prmReqData;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnAcptrVlidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnAcptrVlidResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnAcptrVlidResponseBody Body;
        
        public pubFunBlnAcptrVlidResponse()
        {
        }
        
        public pubFunBlnAcptrVlidResponse(ipg.pubFunBlnAcptrVlidResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnAcptrVlidResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnAcptrVlidResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmStrErr;
        
        public pubFunBlnAcptrVlidResponseBody()
        {
        }
        
        public pubFunBlnAcptrVlidResponseBody(bool pubFunBlnAcptrVlidResult, int prmResult, string prmStrErr)
        {
            this.pubFunBlnAcptrVlidResult = pubFunBlnAcptrVlidResult;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnGetServrDatTimRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnGetServrDatTim", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnGetServrDatTimRequestBody Body;
        
        public pubFunBlnGetServrDatTimRequest()
        {
        }
        
        public pubFunBlnGetServrDatTimRequest(ipg.pubFunBlnGetServrDatTimRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnGetServrDatTimRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmServrDt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmStrErr;
        
        public pubFunBlnGetServrDatTimRequestBody()
        {
        }
        
        public pubFunBlnGetServrDatTimRequestBody(string prmServrDt, int prmResult, string prmStrErr)
        {
            this.prmServrDt = prmServrDt;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pubFunBlnGetServrDatTimResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pubFunBlnGetServrDatTimResponse", Namespace="http://Kimia.org/", Order=0)]
        public ipg.pubFunBlnGetServrDatTimResponseBody Body;
        
        public pubFunBlnGetServrDatTimResponse()
        {
        }
        
        public pubFunBlnGetServrDatTimResponse(ipg.pubFunBlnGetServrDatTimResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Kimia.org/")]
    public partial class pubFunBlnGetServrDatTimResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pubFunBlnGetServrDatTimResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmServrDt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int prmResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmStrErr;
        
        public pubFunBlnGetServrDatTimResponseBody()
        {
        }
        
        public pubFunBlnGetServrDatTimResponseBody(bool pubFunBlnGetServrDatTimResult, string prmServrDt, int prmResult, string prmStrErr)
        {
            this.pubFunBlnGetServrDatTimResult = pubFunBlnGetServrDatTimResult;
            this.prmServrDt = prmServrDt;
            this.prmResult = prmResult;
            this.prmStrErr = prmStrErr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface KimiaPayGatewayVerifyWSrvcSoapChannel : ipg.KimiaPayGatewayVerifyWSrvcSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class KimiaPayGatewayVerifyWSrvcSoapClient : System.ServiceModel.ClientBase<ipg.KimiaPayGatewayVerifyWSrvcSoap>, ipg.KimiaPayGatewayVerifyWSrvcSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KimiaPayGatewayVerifyWSrvcSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KimiaPayGatewayVerifyWSrvcSoapClient.GetBindingForEndpoint(endpointConfiguration), KimiaPayGatewayVerifyWSrvcSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaPayGatewayVerifyWSrvcSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KimiaPayGatewayVerifyWSrvcSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaPayGatewayVerifyWSrvcSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KimiaPayGatewayVerifyWSrvcSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaPayGatewayVerifyWSrvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.TestServiceResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.TestServiceAsync(ipg.TestServiceRequest request)
        {
            return base.Channel.TestServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.TestServiceResponse> TestServiceAsync()
        {
            ipg.TestServiceRequest inValue = new ipg.TestServiceRequest();
            inValue.Body = new ipg.TestServiceRequestBody();
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).TestServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayByDocNoResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnVerifyPayGatewayByDocNoAsync(ipg.pubFunBlnVerifyPayGatewayByDocNoRequest request)
        {
            return base.Channel.pubFunBlnVerifyPayGatewayByDocNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayByDocNoResponse> pubFunBlnVerifyPayGatewayByDocNoAsync(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmRetData, int prmResult, string prmStrErr)
        {
            ipg.pubFunBlnVerifyPayGatewayByDocNoRequest inValue = new ipg.pubFunBlnVerifyPayGatewayByDocNoRequest();
            inValue.Body = new ipg.pubFunBlnVerifyPayGatewayByDocNoRequestBody();
            inValue.Body.prmAcptrCod = prmAcptrCod;
            inValue.Body.prmTrmnlCod = prmTrmnlCod;
            inValue.Body.prmReqData = prmReqData;
            inValue.Body.prmRetData = prmRetData;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnVerifyPayGatewayByDocNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnVerifyPayGatewayAsync(ipg.pubFunBlnVerifyPayGatewayRequest request)
        {
            return base.Channel.pubFunBlnVerifyPayGatewayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnVerifyPayGatewayResponse> pubFunBlnVerifyPayGatewayAsync(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmRetData, int prmResult, string prmStrErr)
        {
            ipg.pubFunBlnVerifyPayGatewayRequest inValue = new ipg.pubFunBlnVerifyPayGatewayRequest();
            inValue.Body = new ipg.pubFunBlnVerifyPayGatewayRequestBody();
            inValue.Body.prmAcptrCod = prmAcptrCod;
            inValue.Body.prmTrmnlCod = prmTrmnlCod;
            inValue.Body.prmReqData = prmReqData;
            inValue.Body.prmRetData = prmRetData;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnVerifyPayGatewayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineReverseResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnRegOnlineReverseAsync(ipg.pubFunBlnRegOnlineReverseRequest request)
        {
            return base.Channel.pubFunBlnRegOnlineReverseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineReverseResponse> pubFunBlnRegOnlineReverseAsync(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmResult, string prmStrErr)
        {
            ipg.pubFunBlnRegOnlineReverseRequest inValue = new ipg.pubFunBlnRegOnlineReverseRequest();
            inValue.Body = new ipg.pubFunBlnRegOnlineReverseRequestBody();
            inValue.Body.prmAcptrCod = prmAcptrCod;
            inValue.Body.prmTrmnlCod = prmTrmnlCod;
            inValue.Body.prmReqData = prmReqData;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnRegOnlineReverseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineConfirmResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnRegOnlineConfirmAsync(ipg.pubFunBlnRegOnlineConfirmRequest request)
        {
            return base.Channel.pubFunBlnRegOnlineConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnRegOnlineConfirmResponse> pubFunBlnRegOnlineConfirmAsync(string prmAcptrCod, string prmTrmnlCod, string prmReqData, string prmResult, string prmStrErr)
        {
            ipg.pubFunBlnRegOnlineConfirmRequest inValue = new ipg.pubFunBlnRegOnlineConfirmRequest();
            inValue.Body = new ipg.pubFunBlnRegOnlineConfirmRequestBody();
            inValue.Body.prmAcptrCod = prmAcptrCod;
            inValue.Body.prmTrmnlCod = prmTrmnlCod;
            inValue.Body.prmReqData = prmReqData;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnRegOnlineConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnAcptrVlidResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnAcptrVlidAsync(ipg.pubFunBlnAcptrVlidRequest request)
        {
            return base.Channel.pubFunBlnAcptrVlidAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnAcptrVlidResponse> pubFunBlnAcptrVlidAsync(string prmAcptrCod, string prmTrmnlCod, string prmReqData, int prmResult, string prmStrErr)
        {
            ipg.pubFunBlnAcptrVlidRequest inValue = new ipg.pubFunBlnAcptrVlidRequest();
            inValue.Body = new ipg.pubFunBlnAcptrVlidRequestBody();
            inValue.Body.prmAcptrCod = prmAcptrCod;
            inValue.Body.prmTrmnlCod = prmTrmnlCod;
            inValue.Body.prmReqData = prmReqData;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnAcptrVlidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipg.pubFunBlnGetServrDatTimResponse> ipg.KimiaPayGatewayVerifyWSrvcSoap.pubFunBlnGetServrDatTimAsync(ipg.pubFunBlnGetServrDatTimRequest request)
        {
            return base.Channel.pubFunBlnGetServrDatTimAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipg.pubFunBlnGetServrDatTimResponse> pubFunBlnGetServrDatTimAsync(string prmServrDt, int prmResult, string prmStrErr)
        {
            ipg.pubFunBlnGetServrDatTimRequest inValue = new ipg.pubFunBlnGetServrDatTimRequest();
            inValue.Body = new ipg.pubFunBlnGetServrDatTimRequestBody();
            inValue.Body.prmServrDt = prmServrDt;
            inValue.Body.prmResult = prmResult;
            inValue.Body.prmStrErr = prmStrErr;
            return ((ipg.KimiaPayGatewayVerifyWSrvcSoap)(this)).pubFunBlnGetServrDatTimAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KimiaPayGatewayVerifyWSrvcSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.KimiaPayGatewayVerifyWSrvcSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KimiaPayGatewayVerifyWSrvcSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ipg.ikcu.com:8033/KimiaPayGatewayVerifyWSrvc.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.KimiaPayGatewayVerifyWSrvcSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ipg.ikcu.com:8033/KimiaPayGatewayVerifyWSrvc.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            KimiaPayGatewayVerifyWSrvcSoap,
            
            KimiaPayGatewayVerifyWSrvcSoap12,
        }
    }
}
